// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unite.Data.Services;

namespace Unite.Data.Migrations.Migrations
{
    [DbContext(typeof(UniteDbContext))]
    [Migration("20201230132947_Root")]
    partial class Root
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Unite.Data.Entities.Cells.CellLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DonorId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("GcimpMethylation")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("GeneExpressionSubtypeId")
                        .HasColumnType("int");

                    b.Property<int?>("IdhMutationId")
                        .HasColumnType("int");

                    b.Property<int?>("IdhStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("MethylationStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("MethylationSubtypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("GeneExpressionSubtypeId");

                    b.HasIndex("IdhMutationId");

                    b.HasIndex("IdhStatusId");

                    b.HasIndex("MethylationStatusId");

                    b.HasIndex("MethylationSubtypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("TypeId");

                    b.ToTable("CellLines");
                });

            modelBuilder.Entity("Unite.Data.Entities.Cells.CellLineInfo", b =>
                {
                    b.Property<int>("CellLineId")
                        .HasColumnType("int");

                    b.Property<string>("AtccLink")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("DepositorEstablishment")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DepositorName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("EstablishmentYear")
                        .HasColumnType("datetime");

                    b.Property<string>("ExPasyLink")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("FirstPublication")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("CellLineId");

                    b.ToTable("CellLineInfos");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.ClinicalData", b =>
                {
                    b.Property<string>("DonorId")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("AgeCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<int?>("KpsBaseline")
                        .HasColumnType("int");

                    b.Property<int?>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProgressionDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProgressionFreeDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RelapseDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("RelapseFreeDays")
                        .HasColumnType("int");

                    b.Property<bool?>("SteroidsBaseline")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SurvivalDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VitalStatusChangeDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("VitalStatusId")
                        .HasColumnType("int");

                    b.HasKey("DonorId");

                    b.HasIndex("AgeCategoryId");

                    b.HasIndex("GenderId");

                    b.HasIndex("LocalizationId");

                    b.HasIndex("VitalStatusId");

                    b.ToTable("ClinicalData");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Donor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Diagnosis")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("DiagnosisDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("MtaProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Origin")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("PrimarySiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimarySiteId");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Localization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.PrimarySite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("PrimarySites");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Therapy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Therapies");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Treatment", b =>
                {
                    b.Property<string>("DonorId")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TherapyId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Results")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("DonorId", "TherapyId");

                    b.HasIndex("TherapyId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Contig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Contigs");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Gene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Genes");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Mutation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlternateAllele")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("ChromosomeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("ContigId")
                        .HasColumnType("int");

                    b.Property<int?>("GeneId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceAllele")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("SequenceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code");

                    b.HasIndex("ChromosomeId");

                    b.HasIndex("ContigId");

                    b.HasIndex("GeneId");

                    b.HasIndex("SequenceTypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Mutations");
                });

            modelBuilder.Entity("Unite.Data.Entities.Samples.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CellLineId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("DonorId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Link")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("SubtypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CellLineId");

                    b.HasIndex("DonorId");

                    b.HasIndex("SubtypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Unite.Data.Entities.Samples.SampleMutation", b =>
                {
                    b.Property<int>("SampleId")
                        .HasColumnType("int");

                    b.Property<int>("MutationId")
                        .HasColumnType("int");

                    b.Property<string>("Filter")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("Quality")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("SampleId", "MutationId");

                    b.HasIndex("MutationId");

                    b.ToTable("SampleMutations");
                });

            modelBuilder.Entity("Unite.Data.Entities.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("Unite.Data.Entities.StudyDonor", b =>
                {
                    b.Property<int>("StudyId")
                        .HasColumnType("int");

                    b.Property<string>("DonorId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("StudyId", "DonorId");

                    b.HasIndex("DonorId");

                    b.ToTable("StudyDonors");
                });

            modelBuilder.Entity("Unite.Data.Entities.Tasks.CellLineIndexingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CellLineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CellLineId");

                    b.ToTable("CellLineIndexingTasks");
                });

            modelBuilder.Entity("Unite.Data.Entities.Tasks.DonorIndexingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("DonorId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.ToTable("DonorIndexingTasks");
                });

            modelBuilder.Entity("Unite.Data.Entities.Tasks.MutationIndexingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("MutationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MutationId");

                    b.ToTable("MutationIndexingTasks");
                });

            modelBuilder.Entity("Unite.Data.Entities.WorkPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WorkPackages");
                });

            modelBuilder.Entity("Unite.Data.Entities.WorkPackageDonor", b =>
                {
                    b.Property<int>("WorkPackageId")
                        .HasColumnType("int");

                    b.Property<string>("DonorId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("WorkPackageId", "DonorId");

                    b.HasIndex("DonorId");

                    b.ToTable("WorkPackageDonors");
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.CellLineType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("CellLineTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GSC",
                            Value = "GSC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Suspension",
                            Value = "Suspension"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.GeneExpressionSubtype>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("GeneExpressionSubtypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classical",
                            Value = "Classical"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mesenchymal",
                            Value = "Mesenchymal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Proneural",
                            Value = "Proneural"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.IDHMutation>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("IDHMutations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IDH1 R132H",
                            Value = "IDH1 R132H"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IDH1 R132C",
                            Value = "IDH1 R132C"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IDH1 R132G",
                            Value = "IDH1 R132G"
                        },
                        new
                        {
                            Id = 4,
                            Name = "IDH1 R132L",
                            Value = "IDH1 R132L"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IDH1 R132S",
                            Value = "IDH1 R132S"
                        },
                        new
                        {
                            Id = 6,
                            Name = "IDH2 R172G",
                            Value = "IDH2 R172G"
                        },
                        new
                        {
                            Id = 7,
                            Name = "IDH2 R172W",
                            Value = "IDH2 R172W"
                        },
                        new
                        {
                            Id = 8,
                            Name = "IDH2 R172K",
                            Value = "IDH2 R172K"
                        },
                        new
                        {
                            Id = 9,
                            Name = "IDH2 R172T",
                            Value = "IDH2 R172T"
                        },
                        new
                        {
                            Id = 10,
                            Name = "IDH2 R172M",
                            Value = "IDH2 R172M"
                        },
                        new
                        {
                            Id = 11,
                            Name = "IDH2 R172S",
                            Value = "IDH2 R172S"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.IDHStatus>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("IDHStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "WildType",
                            Value = "WildType"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mutant",
                            Value = "Mutant"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.MethylationStatus>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MethylationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Unmethylated",
                            Value = "Unmethylated"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Methylated",
                            Value = "Methylated"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.MethylationSubtype>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MethylationSubtypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "H3-K27",
                            Value = "H3-K27"
                        },
                        new
                        {
                            Id = 2,
                            Name = "H3-G34",
                            Value = "H3-G34"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RTKI",
                            Value = "RTKI"
                        },
                        new
                        {
                            Id = 4,
                            Name = "RTKII",
                            Value = "RTKII"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mesenchymal",
                            Value = "Mesenchymal"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.Species>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human",
                            Value = "Human"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mouse",
                            Value = "Mouse"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.AgeCategory>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("AgeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pediatric",
                            Value = "Pediatric"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adult",
                            Value = "Adult"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.Gender>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Female",
                            Value = "Female"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Male",
                            Value = "Male"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Other",
                            Value = "Other"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.VitalStatus>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("VitalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Living",
                            Value = "Living"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Deceased",
                            Value = "Deceased"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.Chromosome>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Chromosomes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chromosome 1",
                            Value = "1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chromosome 2",
                            Value = "2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chromosome 3",
                            Value = "3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chromosome 4",
                            Value = "4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chromosome 5",
                            Value = "5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Chromosome 6",
                            Value = "6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chromosome 7",
                            Value = "7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Chromosome 8",
                            Value = "8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Chromosome 9",
                            Value = "9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Chromosome 10",
                            Value = "10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Chromosome 11",
                            Value = "11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Chromosome 12",
                            Value = "12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Chromosome 13",
                            Value = "13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Chromosome 14",
                            Value = "14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Chromosome 15",
                            Value = "15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Chromosome 16",
                            Value = "16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Chromosome 17",
                            Value = "17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Chromosome 18",
                            Value = "18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Chromosome 19",
                            Value = "19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Chromosome 20",
                            Value = "20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Chromosome 21",
                            Value = "21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Chromosome 22",
                            Value = "22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Chromosome X",
                            Value = "X"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Chromosome Y",
                            Value = "Y"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.MutationType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MutationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single Nucleotide Variant",
                            Value = "SNV"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Insertion",
                            Value = "INS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Deletion",
                            Value = "DEL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Multiple Nucleotide Variant",
                            Value = "MNV"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.SequenceType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("SequenceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coding DNA",
                            Value = "c"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Non Coding DNA",
                            Value = "n"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Linear Genomic DNA",
                            Value = "g"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Curcular Genomic DNA",
                            Value = "o"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mitochondrial DNA",
                            Value = "m"
                        },
                        new
                        {
                            Id = 6,
                            Name = "RNA",
                            Value = "r"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Protein",
                            Value = "p"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Samples.Enums.SampleSubtype>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("SampleSubtypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Primary",
                            Value = "Primary"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Recurrent",
                            Value = "Recurrent"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Samples.Enums.SampleType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("SampleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Control",
                            Value = "Control"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tumor",
                            Value = "Tumor"
                        });
                });

            modelBuilder.Entity("Unite.Data.Entities.Cells.CellLine", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany("CellLines")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.GeneExpressionSubtype>", null)
                        .WithMany()
                        .HasForeignKey("GeneExpressionSubtypeId");

                    b.HasOne("Unite.Data.Entities.Cells.CellLine", null)
                        .WithMany("Childern")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.IDHMutation>", null)
                        .WithMany()
                        .HasForeignKey("IdhMutationId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.IDHStatus>", null)
                        .WithMany()
                        .HasForeignKey("IdhStatusId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.MethylationStatus>", null)
                        .WithMany()
                        .HasForeignKey("MethylationStatusId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.MethylationSubtype>", null)
                        .WithMany()
                        .HasForeignKey("MethylationSubtypeId");

                    b.HasOne("Unite.Data.Entities.Cells.CellLine", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.Species>", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Cells.Enums.CellLineType>", null)
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("Unite.Data.Entities.Cells.CellLineInfo", b =>
                {
                    b.HasOne("Unite.Data.Entities.Cells.CellLine", null)
                        .WithOne("CellLineInfo")
                        .HasForeignKey("Unite.Data.Entities.Cells.CellLineInfo", "CellLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.ClinicalData", b =>
                {
                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.AgeCategory>", null)
                        .WithMany()
                        .HasForeignKey("AgeCategoryId");

                    b.HasOne("Unite.Data.Entities.Donors.Donor", null)
                        .WithOne("ClinicalData")
                        .HasForeignKey("Unite.Data.Entities.Donors.ClinicalData", "DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.Gender>", null)
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("Unite.Data.Entities.Donors.Localization", "Localization")
                        .WithMany()
                        .HasForeignKey("LocalizationId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.VitalStatus>", null)
                        .WithMany()
                        .HasForeignKey("VitalStatusId");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Donor", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.PrimarySite", "PrimarySite")
                        .WithMany()
                        .HasForeignKey("PrimarySiteId");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Treatment", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany("Treatments")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.Donors.Therapy", "Therapy")
                        .WithMany()
                        .HasForeignKey("TherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Mutation", b =>
                {
                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.Chromosome>", null)
                        .WithMany()
                        .HasForeignKey("ChromosomeId");

                    b.HasOne("Unite.Data.Entities.Mutations.Contig", "Contig")
                        .WithMany()
                        .HasForeignKey("ContigId");

                    b.HasOne("Unite.Data.Entities.Mutations.Gene", "Gene")
                        .WithMany("Mutations")
                        .HasForeignKey("GeneId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.SequenceType>", null)
                        .WithMany()
                        .HasForeignKey("SequenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.MutationType>", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Samples.Sample", b =>
                {
                    b.HasOne("Unite.Data.Entities.Cells.CellLine", "CellLine")
                        .WithMany("Samples")
                        .HasForeignKey("CellLineId");

                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany("Samples")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Samples.Enums.SampleSubtype>", null)
                        .WithMany()
                        .HasForeignKey("SubtypeId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Samples.Enums.SampleType>", null)
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("Unite.Data.Entities.Samples.SampleMutation", b =>
                {
                    b.HasOne("Unite.Data.Entities.Mutations.Mutation", "Mutation")
                        .WithMany("MutationSamples")
                        .HasForeignKey("MutationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.Samples.Sample", "Sample")
                        .WithMany("SampleMutations")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.StudyDonor", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany("DonorStudies")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.Study", "Study")
                        .WithMany("StudyDonors")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Tasks.CellLineIndexingTask", b =>
                {
                    b.HasOne("Unite.Data.Entities.Cells.CellLine", "CellLine")
                        .WithMany()
                        .HasForeignKey("CellLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Tasks.DonorIndexingTask", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Tasks.MutationIndexingTask", b =>
                {
                    b.HasOne("Unite.Data.Entities.Mutations.Mutation", "Mutation")
                        .WithMany()
                        .HasForeignKey("MutationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.WorkPackageDonor", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany("DonorWorkPackages")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.WorkPackage", "WorkPackage")
                        .WithMany("WorkPackageDonors")
                        .HasForeignKey("WorkPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
