// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unite.Data.Services;

namespace Unite.Data.Migrations.Migrations
{
    [DbContext(typeof(UniteDbContext))]
    [Migration("20210126103752_Root")]
    partial class Root
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Unite.Data.Entities.Donors.ClinicalData", b =>
                {
                    b.Property<string>("DonorId")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("AgeCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<int?>("KpsBaseline")
                        .HasColumnType("int");

                    b.Property<int?>("LocalizationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProgressionDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProgressionFreeDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RelapseDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("RelapseFreeDays")
                        .HasColumnType("int");

                    b.Property<bool?>("SteroidsBaseline")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SurvivalDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VitalStatusChangeDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("VitalStatusId")
                        .HasColumnType("int");

                    b.HasKey("DonorId");

                    b.HasIndex("AgeCategoryId");

                    b.HasIndex("GenderId");

                    b.HasIndex("LocalizationId");

                    b.HasIndex("VitalStatusId");

                    b.ToTable("ClinicalData");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Donor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Diagnosis")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("DiagnosisDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("MtaProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Origin")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("PrimarySiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimarySiteId");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Localization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.PrimarySite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("PrimarySites");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.StudyDonor", b =>
                {
                    b.Property<int>("StudyId")
                        .HasColumnType("int");

                    b.Property<string>("DonorId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("StudyId", "DonorId");

                    b.HasIndex("DonorId");

                    b.ToTable("StudyDonors");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Therapy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Therapies");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Treatment", b =>
                {
                    b.Property<string>("DonorId")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TherapyId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Results")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("DonorId", "TherapyId");

                    b.HasIndex("TherapyId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.WorkPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("WorkPackages");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.WorkPackageDonor", b =>
                {
                    b.Property<int>("WorkPackageId")
                        .HasColumnType("int");

                    b.Property<string>("DonorId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("WorkPackageId", "DonorId");

                    b.HasIndex("DonorId");

                    b.ToTable("WorkPackageDonors");
                });

            modelBuilder.Entity("Unite.Data.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.AnalysedSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnalysisId")
                        .HasColumnType("int");

                    b.Property<int>("SampleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("AnalysisId", "SampleId");

                    b.HasIndex("SampleId");

                    b.ToTable("AnalysedSamples");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("DonorId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Contig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Contigs");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Gene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Genes");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.MatchedSample", b =>
                {
                    b.Property<int>("AnalysedSampleId")
                        .HasColumnType("int");

                    b.Property<int>("MatchedSampleId")
                        .HasColumnType("int");

                    b.HasKey("AnalysedSampleId", "MatchedSampleId");

                    b.HasIndex("MatchedSampleId");

                    b.ToTable("MatchedSamples");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Mutation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlternateBase")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("ChromosomeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("ContigId")
                        .HasColumnType("int");

                    b.Property<int?>("GeneId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceBase")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("SequenceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code");

                    b.HasIndex("ChromosomeId");

                    b.HasIndex("ContigId");

                    b.HasIndex("GeneId");

                    b.HasIndex("SequenceTypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Mutations");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.MutationOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnalysedSampleId")
                        .HasColumnType("int");

                    b.Property<int>("MutationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("AnalysedSampleId", "MutationId");

                    b.HasIndex("MutationId");

                    b.ToTable("MutationOccurrences");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("DonorId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("SubtypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("SubtypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Unite.Data.Entities.Tasks.DonorIndexingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("DonorId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.ToTable("DonorIndexingTasks");
                });

            modelBuilder.Entity("Unite.Data.Entities.Tasks.MutationIndexingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("MutationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MutationId");

                    b.ToTable("MutationIndexingTasks");
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.AgeCategory>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("AgeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pediatric",
                            Value = "Pediatric"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adult",
                            Value = "Adult"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.Gender>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Female",
                            Value = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Male",
                            Value = "Male"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Other",
                            Value = "Other"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.VitalStatus>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("VitalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Living",
                            Value = "Living"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Deceased",
                            Value = "Deceased"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.AnalysisType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("AnalysisTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "WGS",
                            Value = "WGS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "WES",
                            Value = "WES"
                        },
                        new
                        {
                            Id = 3,
                            Name = "WGA",
                            Value = "WGA"
                        },
                        new
                        {
                            Id = 4,
                            Name = "RNASeq",
                            Value = "RNASeq"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Validation",
                            Value = "Validation"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Amplicon",
                            Value = "Amplicon"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.Chromosome>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Chromosomes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chromosome 1",
                            Value = "1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chromosome 2",
                            Value = "2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chromosome 3",
                            Value = "3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chromosome 4",
                            Value = "4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chromosome 5",
                            Value = "5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Chromosome 6",
                            Value = "6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chromosome 7",
                            Value = "7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Chromosome 8",
                            Value = "8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Chromosome 9",
                            Value = "9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Chromosome 10",
                            Value = "10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Chromosome 11",
                            Value = "11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Chromosome 12",
                            Value = "12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Chromosome 13",
                            Value = "13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Chromosome 14",
                            Value = "14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Chromosome 15",
                            Value = "15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Chromosome 16",
                            Value = "16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Chromosome 17",
                            Value = "17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Chromosome 18",
                            Value = "18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Chromosome 19",
                            Value = "19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Chromosome 20",
                            Value = "20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Chromosome 21",
                            Value = "21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Chromosome 22",
                            Value = "22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Chromosome X",
                            Value = "X"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Chromosome Y",
                            Value = "Y"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.MutationType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MutationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single Nucleotide Variant",
                            Value = "SNV"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Insertion",
                            Value = "INS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Deletion",
                            Value = "DEL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Multiple Nucleotide Variant",
                            Value = "MNV"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.SampleSubtype>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("SampleSubtypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Primary",
                            Value = "Primary"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Recurrent",
                            Value = "Recurrent"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.SampleType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("SampleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Control",
                            Value = "Control"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tumor",
                            Value = "Tumor"
                        });
                });

            modelBuilder.Entity("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.SequenceType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("SequenceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coding DNA",
                            Value = "c"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Non Coding DNA",
                            Value = "n"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Linear Genomic DNA",
                            Value = "g"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Curcular Genomic DNA",
                            Value = "o"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mitochondrial DNA",
                            Value = "m"
                        },
                        new
                        {
                            Id = 6,
                            Name = "RNA",
                            Value = "r"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Protein",
                            Value = "p"
                        });
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.ClinicalData", b =>
                {
                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.AgeCategory>", null)
                        .WithMany()
                        .HasForeignKey("AgeCategoryId");

                    b.HasOne("Unite.Data.Entities.Donors.Donor", null)
                        .WithOne("ClinicalData")
                        .HasForeignKey("Unite.Data.Entities.Donors.ClinicalData", "DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.Gender>", null)
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("Unite.Data.Entities.Donors.Localization", "Localization")
                        .WithMany()
                        .HasForeignKey("LocalizationId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Donors.Enums.VitalStatus>", null)
                        .WithMany()
                        .HasForeignKey("VitalStatusId");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Donor", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.PrimarySite", "PrimarySite")
                        .WithMany()
                        .HasForeignKey("PrimarySiteId");
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.StudyDonor", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany("DonorStudies")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.Donors.Study", "Study")
                        .WithMany("StudyDonors")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.Treatment", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany("Treatments")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.Donors.Therapy", "Therapy")
                        .WithMany()
                        .HasForeignKey("TherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Donors.WorkPackageDonor", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany("DonorWorkPackages")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.Donors.WorkPackage", "WorkPackage")
                        .WithMany("WorkPackageDonors")
                        .HasForeignKey("WorkPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.AnalysedSample", b =>
                {
                    b.HasOne("Unite.Data.Entities.Mutations.Analysis", "Analysis")
                        .WithMany("AnalysedSamples")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.Mutations.Sample", "Sample")
                        .WithMany("SampleAnalises")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Analysis", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany("Analyses")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.File", "File")
                        .WithOne()
                        .HasForeignKey("Unite.Data.Entities.Mutations.Analysis", "FileId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.AnalysisType>", null)
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.MatchedSample", b =>
                {
                    b.HasOne("Unite.Data.Entities.Mutations.AnalysedSample", "Analysed")
                        .WithMany("MatchedSamples")
                        .HasForeignKey("AnalysedSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.Mutations.AnalysedSample", "Matched")
                        .WithMany()
                        .HasForeignKey("MatchedSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Mutation", b =>
                {
                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.Chromosome>", null)
                        .WithMany()
                        .HasForeignKey("ChromosomeId");

                    b.HasOne("Unite.Data.Entities.Mutations.Contig", "Contig")
                        .WithMany()
                        .HasForeignKey("ContigId");

                    b.HasOne("Unite.Data.Entities.Mutations.Gene", "Gene")
                        .WithMany("Mutations")
                        .HasForeignKey("GeneId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.SequenceType>", null)
                        .WithMany()
                        .HasForeignKey("SequenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.MutationType>", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.MutationOccurrence", b =>
                {
                    b.HasOne("Unite.Data.Entities.Mutations.AnalysedSample", "AnalysedSample")
                        .WithMany("MutationOccurrences")
                        .HasForeignKey("AnalysedSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Entities.Mutations.Mutation", "Mutation")
                        .WithMany("MutationOccurrences")
                        .HasForeignKey("MutationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Mutations.Sample", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany("Samples")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.SampleSubtype>", null)
                        .WithMany()
                        .HasForeignKey("SubtypeId");

                    b.HasOne("Unite.Data.Services.Entities.EnumValue<Unite.Data.Entities.Mutations.Enums.SampleType>", null)
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("Unite.Data.Entities.Tasks.DonorIndexingTask", b =>
                {
                    b.HasOne("Unite.Data.Entities.Donors.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unite.Data.Entities.Tasks.MutationIndexingTask", b =>
                {
                    b.HasOne("Unite.Data.Entities.Mutations.Mutation", "Mutation")
                        .WithMany()
                        .HasForeignKey("MutationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
